# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release

addons:
  apt:
    packages:
      - libgit2-dev
